### ISSUE TITLE
Raspotify with Alsamixer can’t declare device

### ISSUE THREAD

**Issue by imstupidwithlinux** [dtcooper/raspotify#569] opened 2022-08-27 20:38 UTC
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

So I’m trying to use raspotify with the alsamixer equalizer „equal“ the soundcard isn’t listed anywhere but you can open it with alsamixer -D equal I tried to do —device equal and in asound.conf equal but it doesn’t work

**Comment by JasonLG1979** [comment] 2022-08-27 21:27
Duplicate of https://github.com/dtcooper/raspotify/issues/475 & https://github.com/dtcooper/raspotify/issues/23

The ALSA equalizer is unmaintained. It hasn't been updated in over ten years, and a lot has changed in that time. It doesn't work because it requires a `~/` for it's config and the Raspotify systemd service dynamic user doesn't have a `~/`.

**Closed** 2022-08-27 21:28 UTC
Labels: invalid, not our bug
