### ISSUE TITLE
Raspotify not visible when my phone is the access point

### ISSUE THREAD

**Issue by Bram-diederik** [dtcooper/raspotify#409] opened 2021-07-20 14:33 UTC
I have a pi zero w with a bluetooth speaker.
Works great. But only the pi is not visible if i use my phone as access point. (And i have no wifi connected on my phone need to test that out. Im reinstalling after i gave volumio one go)

I have premium and my device credentials set in the config.

**Comment by Bram-diederik** [comment] 2021-07-24 16:38
![Screenshot_20210724-183618_Spotify](https://user-images.githubusercontent.com/53519837/126875151-87d81bf8-0c8f-4ba7-a8c6-158d30900b1f.jpg)
![Screenshot_20210724-183557_Spotify](https://user-images.githubusercontent.com/53519837/126875152-6a3e39ed-8128-4445-87f2-d11f0e02e9b6.jpg)

The chromecast works fine. Is connected to my phone hotspot. Raspotify only accessible when my phone is connected to a wifi network.

**Comment by Ej747** [comment] 2021-08-04 02:23
I have the same problem where I can only use it if my phone is connected to a wifi network

**Comment by Bram-diederik** [comment] 2021-08-04 05:00
Well after reboot the chromecast also looses connection. And is also only available when the wifi is up. Try to get this bug to spotify support but that is slow.

**Comment by JasonLG1979** [comment] 2021-11-17 02:40
duplicate of https://github.com/dtcooper/raspotify/issues/413

**Closed by JasonLG1979** 2021-11-17 02:40 UTC
