### ISSUE TITLE
Output to pipe?

### ISSUE THREAD

**Issue by mrpete69** [dtcooper/raspotify#540] opened 2022-04-23 11:14 UTC
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

I’ve used raspotify for some years combined with snapcast in a multiroom environment, with several rpi+hifiberry beocreate. Now I’m building a new system for one of my kids and don’t understand how to make it work in the new configuration. I’ve googled and tested lots of different ways to get it right, but can’t figure out. Pipe as backend seems obvious, but then I’m stuck. 
In the old raspotify I had this combination of pipe and device: BACKEND_ARGS="--backend pipe --device /tmp/snapfifo"
How should I write this in /etc/raspotify/conf?

**Comment by JasonLG1979** [comment] 2022-04-23 15:48
Duplicate of  https://github.com/dtcooper/raspotify/issues/498

**Closed by JasonLG1979** 2022-04-23 15:48 UTC

**Comment by timglong** [comment] 2022-04-24 18:06
@mrpete69 Check out my update on #498, let me know if I can help! Took me 5 minutes or so to get everything working again. Woo!

**Comment by mrpete69** [comment] 2022-04-26 18:32
@timglong Thanks a lot! Worked perfectly!
